name: ${project.name}
version: ${project.version}
description: '${project.description}'
depend: [FlexCore]
softdepend: []
authors: [${project.authors}]
website: ${project.url}
main: ${project.mainClass}
commands:
  flexping:
    description: 'Base ping modification command'
    aliases: [fping]

permissions:
  ##########
  # Groups #
  ##########
  flexmotd.admin:
    default: op
    children:
      flexmotd.ping.group.list: true
      flexmotd.ping.group.set: true
      flexmotd.ping.image.list: true
      flexmotd.ping.image.set: true
      flexmotd.ping.message.list: true
      flexmotd.ping.message.set: true

  #########
  # Nodes #
  #########
  flexmotd.ping.group.list:
    description: 'Ability to list ping information groups.'
    default: false
  flexmotd.ping.group.set:
    description: 'Ability to set ping information with a group.'
    default: false

  flexmotd.ping.image.list:
    description: 'Ability to list ping images.'
    default: false
  flexmotd.ping.image.set:
    description: 'Ability to set ping image.'
    default: false

  flexmotd.ping.message.list:
    description: 'Ability to list ping messages.'
    default: false
  flexmotd.ping.message.set:
    description: 'Ability to set ping message.'
    default: false