groups:
  allDefault:
    message: 'default'
    image: 'default'
message:
  messages:
    default: |
      This is the first line
      This is the second line
image:
  images:
    default: 'server-icon.png'